JalopyJournal_MVC/JalopyJournal/Models/Car.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JalopyJournal.Models
{
    public class Car
    {
        public int ID { get; set; }

        [StringLength(500, ErrorMessage = "The {0} value cannot exceed {1} characters. ")]
        [Display(Name = "Description")]
        public string Description { get; set; }
    }
}

JalopyJournal_MVC/JalopyJournal/Controllers/AirFilterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JalopyJournal.DAL;
using JalopyJournal.Models;
using Microsoft.Ajax.Utilities;

namespace JalopyJournal.Controllers
{
    public class AirFilterController : JJController
    {
        public async Task<ActionResult> Index(int? carID, string sortOrder)
        {
            var airFilter = from s in db.AirFilter select s;
            if (carID != null && carID > 0)
            {
                airFilter = airFilter.Where(d => d.CarID == carID);
                ViewBag.CarID = carID;
                UpdateCarDescription(carID);
            }
            
            var sortDirection = ControllerHelper.GetSortOrder(sortOrder);
            UpdateSortDirection(sortDirection);
            airFilter = AirFilterManager.AddSortToQuery(airFilter, sortOrder);

            return View(await airFilter.ToListAsync());
        }

        // GET: AirFilter/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null || id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AirFilter airFilter = await db.AirFilter.FindAsync(id);
            if (airFilter == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (airFilter.CarID != null && airFilter.CarID > 0)
                {
                    ViewBag.CarID = airFilter.CarID;
                    UpdateCarDescription(airFilter.CarID);
                }
            }
            return View(airFilter);
        }

        // GET: AirFilter/Create
        public ActionResult Create(int? carID)
        {
            if (carID != null && carID > 0)
                ViewBag.CarID = carID;
            else
                PopulateCarDropDownList();
            UpdateCarDescription(carID);
            return View();
        }

        // POST: AirFilter/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,FilterType,Miles,Date,Cost,Notes,CarID")] AirFilter airFilter)
        {
            if (ModelState.IsValid)
            {
                db.AirFilter.Add(airFilter);
                await db.SaveChangesAsync();
                return RedirectToAction("Index", new { CarID = airFilter.CarID });
            }

            if (airFilter.CarID > 0)
            {
                ViewBag.CarID = airFilter.CarID;
                UpdateCarDescription(airFilter.CarID);
            }
            return View(airFilter);
        }

        // GET: AirFilter/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null || id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AirFilter airFilter = await db.AirFilter.FindAsync(id);
            if (airFilter == null)
            {
                return HttpNotFound();
            }
            if (airFilter.CarID > 0)
            {
                ViewBag.CarID = airFilter.CarID;
                UpdateCarDescription(airFilter.CarID);
                PopulateCarDropDownList(airFilter.CarID);
            }
            return View(airFilter);
        }

        // POST: AirFilter/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,FilterType,Miles,Date,Cost,Notes,CarID")] AirFilter airFilter)
        {
            if (ModelState.IsValid)
            {
                db.Entry(airFilter).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index", new { CarID = airFilter.CarID });
            }
            if (airFilter.CarID > 0)
            {
                ViewBag.CarID = airFilter.CarID;
                UpdateCarDescription(airFilter.CarID);
                PopulateCarDropDownList(airFilter.CarID);
            }
            return View(airFilter);
        }

        // GET: AirFilter/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null || id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AirFilter airFilter = await db.AirFilter.FindAsync(id);
            if (airFilter == null)
            {
                return HttpNotFound();
            }
            else if (airFilter.CarID > 0)
            {
                ViewBag.CarID = airFilter.CarID;
                UpdateCarDescription(airFilter.CarID);
            }
            return View(airFilter);
        }

        // POST: AirFilter/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            if (id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            AirFilter airFilter = await db.AirFilter.FindAsync(id);
            if (airFilter.CarID > 0)
            {
                ViewBag.CarID = airFilter.CarID;
                UpdateCarDescription(airFilter.CarID);
            }
            db.AirFilter.Remove(airFilter);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JalopyJournal_MVC/JalopyJournal/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JalopyJournal.DAL;
using JalopyJournal.Models;
using JalopyJournal.ViewModels;

namespace JalopyJournal.Controllers
{
    public class CarController : JJController
    {
        // GET: Car
        public async Task<ActionResult> Index(int? carID, string sortOrder)
        {
            var car = from s in db.Car
                            select s;
            if (carID != null && carID > 0)
                car = car.Where(d => d.ID == carID);

            var sortDirection = ControllerHelper.GetSortOrder(sortOrder);
            UpdateSortDirection(sortDirection);
            car = CarManager.AddSortToQuery(car, sortOrder);

            List<Car> carListItems = car.ToList<Car>();
            ViewBag.CarList = carListItems;

            return View(await car.ToListAsync());
        }

        // GET: Car/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null || id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = await db.Car.FindAsync(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // GET: Car/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Car/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Description")] Car car)
        {
            if (ModelState.IsValid)
            {
                db.Car.Add(car);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(car);
        }

        // GET: Car/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null || id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = await db.Car.FindAsync(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // POST: Car/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Description")] Car car)
        {
            if (ModelState.IsValid)
            {
                db.Entry(car).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(car);
        }

        // GET: Car/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null || id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = await db.Car.FindAsync(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // POST: Car/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            if (id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Car car = await db.Car.FindAsync(id);
            db.Car.Remove(car);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        //Car Select Functions
        public ActionResult CarSelector()
        {
            var carList = PopulateCarList();
            return View(carList);
        }

        // Private Functions
        private List<CarIndex> PopulateCarList()
        {   // Provide information for the check box array using the AssignedCourseData view model
            var allCars = db.Car;
            var viewModel = new List<CarIndex>();
            foreach (var carItem in allCars)
            {
                viewModel.Add(new CarIndex
                {
                    ID = carItem.ID,
                    Description = carItem.Description,
                });
            }
            return viewModel;
        }

        //Car Home Funtions
        public ActionResult CarHome(int? carID)
        {
            Car car = db.Car.Find(carID);
            if (car == null)
            {
                return HttpNotFound();
            }
            var viewModel = new CarIndex();
            viewModel.ID = car.ID;
            viewModel.Description = car.Description;
            return View(viewModel);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JalopyJournal_MVC/JalopyJournal/Views/Car/CarHome.cshtml
@model JalopyJournal.ViewModels.CarIndex
@{
    ViewBag.Title = "Car Home";
}
<div class="row">
    <div class="col-md-4">
        <h2 class="title">@Model.Description</h2>

        @Html.ActionLink("Fuel", "Index", "Fuel", new { carID = Model.ID }, new { @class = "btn btn-default carbtn" })
        @Html.ActionLink("Fuel Additive", "Index", "FuelAdditive", new { carID = Model.ID }, new { @class = "btn btn-default carbtn" })
        @Html.ActionLink("Oil Plus Filter", "Index", "OilPlusFilter", new { carID = Model.ID }, new { @class = "btn btn-default carbtn" })
        @Html.ActionLink("Oil Additive", "Index", "OilAdditive", new { carID = Model.ID }, new { @class = "btn btn-default carbtn" })
        @Html.ActionLink("Air Filter", "Index", "AirFilter", new { carID = Model.ID }, new { @class = "btn btn-default carbtn" })
    </div>
</div>
<p>
    @Html.ActionLink("Back to Cars", "CarSelector")
</p>
<style>
    a.carbtn {
        padding: 30px;
        width: 150px;
        height: 80px;
        margin: 5px;
        text-align: center;
        vertical-align: middle;
    }
</style>

JalopyJournal_MVC/JalopyJournal/Views/Car/CarSelector.cshtml
@model IEnumerable<JalopyJournal.ViewModels.CarIndex>
@{
    ViewBag.Title = "Select a Car";
}
<div class="row">
    <div class="col-md-4">
        <h2 class="title">Select a Car</h2>
        <div>
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                @Html.ActionLink(item.Description, "CarHome", "Car", new { carID = item.ID }, new { @class = "btn btn-default carbtn" })
            }
        }
        </div>
        <div style="padding-top: 1em">
            @Html.ActionLink("Enter New Car", "Create", "Car")
        </div>
        <div style="padding-top: 1em">
            @Html.ActionLink("Manage Cars", "Index")
        </div>
    </div>
</div>
<style>
    a.carbtn {
        padding: 30px;
        width: 150px;
        height: 80px;
        margin: 5px;
        text-align: center;
        vertical-align: middle;
    }
</style>

JalopyJournal_MVC/JalopyJournal/Views/Car/Create.cshtml
@model JalopyJournal.Models.Car

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Car</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "CarSelector")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JalopyJournal_MVC/JalopyJournal/Views/Car/Delete.cshtml
@model JalopyJournal.Models.Car

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Car</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JalopyJournal_MVC/JalopyJournal/Views/Car/Details.cshtml
@model JalopyJournal.Models.Car

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Car</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

JalopyJournal_MVC/JalopyJournal/Views/Car/Edit.cshtml
@model JalopyJournal.Models.Car

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Car</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JalopyJournal_MVC/JalopyJournal/Views/Car/Index.cshtml
@model IEnumerable<JalopyJournal.Models.Car>

@{
    ViewBag.Title = "Car";
}

<h2>Car</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Description", "Index", new { sortOrder = "description_" + ViewBag.SortParm })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Back to List", "CarSelector")
</div>